### ISSUE TITLE
Go 1.14.14 / 1.15.7 images

### ISSUE THREAD

**Issue by ConorNevin** [CircleCI-Public/cimg-go#113]
Any idea on the ETA for images using 1.14.14 and 1.15.7?

Release: https://github.com/golang/go/releases/tag/go1.14.14 and https://github.com/golang/go/releases/tag/go1.15.7

**Comment by felicianotech** [comment]
Done 🙂 https://github.com/CircleCI-Public/cimg-go/pull/114
