### ISSUE TITLE
add golangci-lint

### ISSUE THREAD

**Issue by wyardley** [CircleCI-Public/cimg-go#119]
Because the user doesn't exist, using `golangci/golangci-lint` directly for lint steps when using this executor (or the go orb) for other steps doesn't work too well. It would be nice to add the option to have a golangci-lint run step in the go orb as well.

This is Ok for projects without private dependencies (i.e., just run the golangci-lint image separately without using the cache etc. from this step), but with more complicated setups, it would be nice to have golangci-lint baked in.

Would it be possible to bake that into this image, since I imagine it's a common toolset people would like to use (only challenge might be keeping the version up to date)

**Comment by felicianotech** [comment]
A PR is now open for this. Once merged, this Issue will close. `golangci-lint` will be available whenever the next Go releases come out.

**Comment by wyardley** [comment]
Thanks!
