### ISSUE TITLE
Publish images for Go beta and RC versions

### ISSUE THREAD

**Issue by nevkontakte** [CircleCI-Public/cimg-go#133]
Currently [go 1.17rc1](https://groups.google.com/g/golang-announce/c/gJE7OtHlRbM) is available as a preview for the upcoming release. Providing images with beta and rc versions would be very convenient for the users who want to test their projects against the upcoming versions.

Without such images the users have to either not use cimg at all, or have different workflows for stable and preview versions of Go.

**Comment by felicianotech** [comment]
Hi. Thank you for your request. This is already something we are considering for the Convenience Images in the future. You can upote this request on [CircleCI Ideas](https://ideas.circleci.com/images/p/support-beta-and-rc-versions) where we are tracking user interest in this request.

Thanks again!
