### ISSUE TITLE
1.17 should be published as 1.17.0

### ISSUE THREAD

**Issue by jaredallard** [CircleCI-Public/cimg-go#136]
Hey all, mostly a feature request I guess, but it'd be nice if 1.17 could also be published as 1.17.0 (and future 1.X.0 releases) so that we could consume 1.17 images without automatically being upgraded to the latest patch release. This is the same behaviour that `golang` currently follows.

Side note: [Your docs](https://circleci.com/developer/images/image/cimg/go) currently say that 1.17.0 is a valid tag, but it's not.

**Comment by jaredallard** [comment]
I tried to take a quick look at the `shared` infra to see if this was a technical limitation, but it looks like `release.sh` is being called with `v1.17.`. I suspect that's because if Go were to be downloaded with `1.17.0` it'd fail, so there would need to be logic to support processing that. Not 100% sure, but didn't want to try modifying any of that as that seems a little complex and likely to break other things if I touch that area of code and it's not super testable because I don't work here :D

**Comment by felicianotech** [comment]
As you expected, this needs to be addressed in the `shared-tools` repo. This issue will be tracked here instead: https://github.com/CircleCI-Public/cimg-shared/issues/39

Thanks for bringing this up.
