### ISSUE TITLE
Please create go1.17.7 image

### ISSUE THREAD

**Issue by lizthegrey** [CircleCI-Public/cimg-go#153]
go1.17.7 has fixes for some rather critical correctness issues on ARM64. thanks! binaries should be out shortly for https://github.com/golang/go/tree/go1.17.7

**Comment by lizthegrey** [comment]
Announcement is out from go devs.

**Comment by felicianotech** [comment]
They will be out shortly. This Issue will auto close when the PR gets merged.

Thank you.

**Comment by lizthegrey** [comment]
Looks like docker publish failed :( https://app.circleci.com/pipelines/github/CircleCI-Public/cimg-go/337/workflows/4f382460-5427-4037-a3ed-ede4066f107b/jobs/362

**Comment by felicianotech** [comment]
This issue was fixed and the image published.

**Comment by lizthegrey** [comment]
Many thanks!
