### ISSUE TITLE
Golangci-lint support for Go 1.18

### ISSUE THREAD

**Issue by nelzkiddom** [CircleCI-Public/cimg-go#161]
At the time of writing this, `golangci-lint` has bumped up to `v1.45.2` to support Go 1.18.

**Comment by nelzkiddom** [comment]
Not sure if you'd re-publish the Go 1.18 image after this gets merged... But that would be helpful on our end. 🙏

**Comment by felicianotech** [comment]
We typically don't republish but in this case:

1. 1.18 is the most recent version
2. This is technically a bug since the tool won't support this Go version
3. 1.18 came out less than a month ago

This version will be re-spun (re-released) shortly.
