### ISSUE TITLE
Go 1.20 was released...

### ISSUE THREAD

**Issue by marten-seemann** [CircleCI-Public/cimg-go#210]
... and there's no image available here. Why do new Go versions work immediately on GitHub Actions, but not on CircleCI?

**Comment by felicianotech** [comment]
Our policy is that we release new Convenience Images within 48 hours of the upstream release. Go v1.20 was released.... today. There's already a PR open for it and it will be merged soon.

I can't speak for how anything with GitHub Actions works.

**Comment by marten-seemann** [comment]
That was fast! Thank you :)
