### ISSUE TITLE
Update `golangci-lint` version to 1.51.2

### ISSUE THREAD

**Issue by love-bhardwaj** [CircleCI-Public/cimg-go#218]
We use CircleCI images for linting issues in CI. Since introducing generics we have been having problems with `golangci-lint` version to `1.51.1` which local testing suggests are resolved in version `1.51.2`. But CircleCI images having the older version are forcing use the older version leading us to disable linters such `gocritic`.

I can open a PR if required 🙂

**Comment by felicianotech** [comment]
The attached PR, when merged, will resolve and auto-close this issue. The updated version of this tool, `.2`, will be present in the Go v1.19.7 and v1.20.2 images.
