### ISSUE TITLE
Failed to download go dependencies

### ISSUE THREAD

**Issue by asdwsda** [CircleCI-Public/cimg-go#51]
Builds running on `cimg/go:1.13` failing with

```
#!/bin/bash -eo pipefail
go mod download
go: writing go.mod cache: mkdir /go/pkg: permission denied
...
```

**Comment by felicianotech** [comment]
Thanks for reporting. Investigating now.

**Comment by felicianotech** [comment]
This fix will be rolled out within 20 minutes.

**Comment by felicianotech** [comment]
@asdwsda Hey. The fix is deployed. Can you confirm that this image is working for you again?

**Comment by asdwsda** [comment]
@felicianotech tl;dr **yes**, it is working again.

`go mod download` and related steps are working again, but it was a bit trickier than clicking on `Rerun workflow`. Restoring go modules from cache has started to fail, because it tries to extract files to `/go/` and got a `Permission denied` again.
```
Failed to unarchive cache

Error untarring cache: Error extracting tarball /tmp/cache922072060 : tar: go: Cannot mkdir: Permission denied 
```
As far as I know there is no official method to drop cache without cache key modification. That's sad. Hopefully there is a bug (or feature?) I found earlier. Caches are immutable, except one case. For example you have a cache key like this: `gomod-v3-{{ checksum "go.sum" }}`. Changing this to `gomod-v3-{{ checksum "go.sum" }}-something` should create a new cache, but that's not true. Both keys will reference the same cache. So saving to `gomod-v3-{{ checksum "go.sum" }}-something` overwrites `gomod-v3-{{ checksum "go.sum" }}`. This way I was able to fix the cache without touching anything on our `master` branch.

**Comment by felicianotech** [comment]
Hmm. Can you please create a post in CircleCI Discuss for this in the "bug report" section? Also, if you can, provide as much of your config in that post as you can.

Based on specifically what you provided here, caching shouldn't work like that.

**Comment by asdwsda** [comment]
Yeah, sure. I have a minimal config to proof that.

**Comment by Horgix** [comment]
Having the link to the CircleCI Discuss bug report mentioned in the last few comments would be cool since people that encounter this bug naturally end up here - at least it's my case, and I was unable to find any Discuss topic related to this (I probably missed it)

**Comment by jason-riddle** [comment]
Why does the cache key need to be updated? That part was never clarified.

**Comment by felicianotech** [comment]
@jason-riddle It's immutable. So if the cache contains binary data for another version of Go or the wrong architecture, it will stay that way.
