### ISSUE TITLE
publish images based on Ubuntu 20.04 

### ISSUE THREAD

**Issue by fortytw2** [CircleCI-Public/cimg-go#91]
So I've been trying to upgrade to cimg from `circleci/golang` for a hour ish now, hunted down the source of a lot of my problems to this image being based on `cimg/base:2020.06` which is ubuntu 18.04. (`fzf` is only available in the 19 and up ubuntu repos) 

Could y'all add a variant of this image based on `cimg/base:2020.08-20.04` ? I don't think I've missed a release of this based on that version of ubuntu. 

Thanks

**Comment by felicianotech** [comment]
Next-gen Convenience Images will begin to be based on Ubuntu 20.04 starting September 2nd. There's more information on [this CircleCI Discuss thread](https://discuss.circleci.com/t/ubuntu-20-04-next-gen-convenience-images/36604?u=felicianotech) in the section that starts with "Default Ubuntu Version".

Specifically for this image, the first Go release to occur on or after September 2nd will be based on Ubuntu 20.04.

I'll leave this Issue open until then for tracking purposes.

**Comment by fortytw2** [comment]
Thanks for the info @felicianotech - are all technical announcements made via those forums?

**Comment by felicianotech** [comment]
For Convenience Images yes.

Btw, the Go v1.14.9 and v1.15.2 tags will be the first to be based on Ubuntu 20.04.
